version: '2'
services:
  db:
    build:
      context: db
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    # uncomment the following to enable backup
    #environment:
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1
  app:
    build:
      context: app
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
    links:
      - db:db
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro
  web:
    build:
      context: web
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
    ports:
      - "443:443"
    links:
      - app:platform
    volumes:
      - /etc/localtime:/etc/localtime:ro
